import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { League_Spartan } from "next/font/google";
import { leagueSpartan, roboto } from "./utilities/font";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${leagueSpartan.variable} ${roboto.variable} light h-[100%]`}>
				<Sidebar />
				<div className="h-full w-[95%] min-h-screen lg:w-3/4 xl:w-1/2 mx-auto pt-[40px] lg:pt-[60px]">
					<main>{children}</main>
				</div>
			</body>
		</html>
	);
}
